import { render, screen } from '@testing-library/react'
import { describe, it, expect } from 'vitest'

import { HomeCards } from 'components/HomeCards'

describe('HomeCards', () => {
  it('renders welcome message', () => {
    render(<HomeCards />)

    expect(
      screen.getByText("Hello, I'm a component, auto generated by Clingon CLI!")
    ).toBeInTheDocument()
  })
})
