import { render, screen } from '@testing-library/react'
import { describe, it, expect } from 'vitest'

import { VideoPlayerControls } from 'components/VideoPlayerControls'
import { UseVideoPlayer } from 'hooks/useVideoPlayer'

describe('VideoPlayerControls', () => {
  it('renders welcome message', () => {
    render(<VideoPlayerControls resources={{} as UseVideoPlayer} />)

    expect(
      screen.getByText("Hello, I'm a component, auto generated by Clingon CLI!")
    ).toBeInTheDocument()
  })
})
