import { render, screen } from '@testing-library/react'
import { describe, it, expect } from 'vitest'

import { ExpandableImage } from 'components/ExpandableImage'

describe('ExpandableImage', () => {
  it('renders welcome message', () => {
    render(<ExpandableImage />)

    expect(
      screen.getByText("Hello, I'm a component, auto generated by Clingon CLI!")
    ).toBeInTheDocument()
  })
})
